# Generated by Django 3.0.3 on 2020-02-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker_app', '0002_auto_20200204_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='title',
        ),
    ]
