# Generated by Django 3.0.3 on 2020-02-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker_app', '0004_auto_20200205_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied_to',
        ),
        migrations.AlterField(
            model_name='response',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobseeker_app.Job'),
        ),
    ]
